### ISSUE TITLE
请求：支持 Ren'Py 7.5 与 Ren'Py 8

### ISSUE THREAD

**Issue by Liarscake** [imgradeone/DDLCModTemplate-Chinese-next#7]
如题()
英文模板已经支持了()
就是问问什么时候中文模板也能用上()

**Comment by imgradeone** [comment]
抱歉，该项目太久没维护了……

近日可能会直接出 3.0 版本

**Comment by Liarscake** [comment]
> 抱歉，该项目太久没维护了……
> 
> 近日可能会直接出 3.0 版本

好耶！！！！！！！！！！！！！！！！！！！！！！！！！！！
我已经迫不及待了！！！！！！！！！

**Comment by Liarscake** [comment]
> 抱歉，该项目太久没维护了……
> 
> 近日可能会直接出 3.0 版本

呜呜呜呜呜呜呜呜，距离上一次更新已经过去半年了到底什么时候更新呀呜呜呜呜呜呜呜呜

**Comment by imgradeone** [comment]
> > 抱歉，该项目太久没维护了……
> > 近日可能会直接出 3.0 版本
> 
> 呜呜呜呜呜呜呜呜，距离上一次更新已经过去半年了到底什么时候更新呀呜呜呜呜呜呜呜呜

8 月开新仓库（）

**Comment by imgradeone** [comment]
话说，其实我更想直接 drop 掉旧版本，直接从模板 4.0（只支持 Ren'Py 8）下手

**Comment by imgradeone** [comment]
https://github.com/DokiMod/DDLCModTemplate-Chinese-future/tree/python-3

开仓库了，仅支持 Ren'Py 8
